---
title: "PHE States EDA"
author: "Ryan Mersereau"
date: "2026-02-27"
output: pdf_document
---

```{r}
library(tidyverse)
library(dplyr)
library(readxl)
```

```{r}
# Reading in data
orders <- read_excel("C:/Users/gemer/Downloads/Finalordersstates.xlsx")
```

```{r}
#Converting date objects and adding time to delivery variable
orders$dateAndTime <- ymd_hms(orders$dateAndTime, tz = "UTC")

orders$dateAndTime <- as.Date(orders$dateAndTime)
orders$dateAndTime <- format(orders$dateAndTime, format = "%m/%d/%Y")

orders <- orders %>%
  rename(arrival_date = dateAndTime)

orders$arrival_date <- as.Date(orders$arrival_date, format = "%m/%d/%Y")
orders$shipping_date <- as.Date(orders$shipping_date, format = "%m/%d/%Y")

orders <- orders %>%
  mutate(time_to_delivery = difftime(orders$arrival_date, orders$shipping_date, 
                                     units = "days"))

orders$time_to_delivery <- as.integer(orders$time_to_delivery)

orders <- drop_na(orders)
```

```{r}
#Creating table for state data
statesfreq <- orders %>%
  group_by(Ship_State, Ship_Country) %>%
  rename(state = Ship_State) %>%
  summarise(count = n(),
            Mean_delivery_time = mean(time_to_delivery))

statesfreq
```

```{r}
#US Delivery frequency heatmap
library(usmap)
library(ggplot2)

plot_usmap(data = statesfreq, values = "count", regions = "states") +
  scale_fill_gradientn(colours = c("white", "purple", "blue"),
                       name = "Number of orders", label = scales::comma) +
  labs(title = "Order Frequency by state") +
  theme(legend.position = "right")

#US Mean delivery time heatmap

plot_usmap(data = statesfreq, values = "Mean_delivery_time", regions = "states") +
  scale_fill_gradientn(colours = c("green", "yellow", "red"), 
                       name = "Time in days", label = scales::comma) +
  labs(title = "Mean Delivery Time of US Orders") +
  theme(legend.position = "right")


view(countypov)
```

